[package]
name = "InterrupTweet"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
sqlx = { version = "0.8.3", features = ["runtime-tokio", "sqlite"] }
dotenvy = "0.15.0"
